name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Ubuntu-based Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./oci/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/your-repo-name:latest
        build-args: |
          REGISTRY=docker.io
          IMAGE=ubuntu

    - name: Build and push CUDA-based Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./oci/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/your-repo-name:latest
        build-args: |
          REGISTRY=docker.io/nvidia
          IMAGE=cuda:12.4.1-base-ubuntu22.04
